
---
title: "Untitled"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Install relevant packages
```{r}

install.packages('devtools')
install.packages('SeuratObject')
install.packages('Matrix')
devtools::install_github('KChen-lab/METAFlux')
install.packages('osqp')
install.packages('XML')
install.packages('methods')
install.packages('pheatmap')
install.packages('limma')
install.packages('ggplot2')
install.packages('patchwork')
```




Setup
```{r}
setwd("C:\\Users\\antho\\OneDrive\\Desktop\\Misc\\20240727_Sc7a1_RNAseq\\R")


library(XML)

library(pheatmap)


# Custom Scripts
cbrt <- function(x) {
    sign(x) * abs(x)^(1/3)
}

```


1 - Perform METAflux analysis and calculate FLUX
```{r}

library(METAFlux)
library(methods)



#exprData = "C:\\Users\\antho\\OneDrive\\Desktop\\Misc\\20240727_Sc7a1_RNAseq\\R\\DESeq2Norm.txt"
exprData = "C:\\Users\\antho\\OneDrive\\Desktop\\Misc\\20240727_Sc7a1_RNAseq\\R\\TPM_Norm.txt"
outName = 'tpmNorm'
log10_transform = FALSE

exprData = read.table(exprData,
                     sep="\t",
                     header=TRUE)
tpm_row_names = toupper(array(exprData[,1]))
tpm_row_names = make.unique(tpm_row_names)
rownames(exprData) = tpm_row_names
exprData = exprData[,c(2:dim(exprData)[2])]

# Remove rows with NA values
exclude = which(is.na(exprData[,1]))
if (!(length(exclude)==0)){
  exprData = exprData[-exclude,]
}

# Perofrms log transformation if log10_transform=TRUE
if (log10_transform){
  exprData = log10(exprData+1) 
}
       

# Load ancillary files
data("human_gem")
data("cell_medium")

# Acquire reaction scores and calculates flux
scores = calculate_reaction_score(exprData)
flux = compute_flux(mras=scores,
                    medium=cell_medium)

flux=cbrt(flux) # Optional: Cubic root normalization to flux scores

# Save flux variable
write.table(flux,
            file = paste('flux_',outName,'.txt',
                         sep=""),
            append=FALSE,
            sep="\t",
            row.names=TRUE,
            col.names=TRUE)

```

2 - Compare between different transformations
  (1) Compare histograms and standard deviations
  (2) gSlc7a1 vs gBdnf: glycolysis, lysine metabolism
  
```{r}

make_histogram1 = function(data, 
                           bin_num=100, 
                           hist_title) {
  library(ggplot2)
  colnames(data) = 'col_name'
  fig = ggplot(data=data, aes(x = col_name)) + 
    geom_histogram(bins = bin_num) +
    theme_bw() +
    #geom_density(fill="steelblue", alpha=0.5) + 
    theme(
      text = element_text(size=14),
      axis.title = element_text(size=20),
      axis.text = element_text(size=20),
      plot.title = element_text(size=20, face="bold"),
      legend.title = element_text(size=14),
      legend.text = element_text(size=12)
    ) +
    labs(tite=hist_title,
         x="Count", y="Flux Scores") +
    xlim(-0.4, 0.4) + 
    scale_y_log10()
    
    
  return(fig)
}

    
```
  
```{r}

library(ggplot2)
library(patchwork)
library(plotly)



data1 = "C:\\Users\\antho\\OneDrive\\Desktop\\Misc\\20240727_Sc7a1_RNAseq\\Analysis\\20250504_METAfluxAnalysis\\fluxOutputs\\flux_deseq2Norm.txt"
data2 = "C:\\Users\\antho\\OneDrive\\Desktop\\Misc\\20240727_Sc7a1_RNAseq\\Analysis\\20250504_METAfluxAnalysis\\fluxOutputs\\flux_deseq2Norm_log10.txt"
data3 = "C:\\Users\\antho\\OneDrive\\Desktop\\Misc\\20240727_Sc7a1_RNAseq\\Analysis\\20250504_METAfluxAnalysis\\fluxOutputs\\flux_tpmNorm.txt"
data4 = "C:\\Users\\antho\\OneDrive\\Desktop\\Misc\\20240727_Sc7a1_RNAseq\\Analysis\\20250504_METAfluxAnalysis\\fluxOutputs\\flux_tpmNorm_log10.txt"


flux1 = read.table(data1,
                   row.names=1,
                   header=TRUE)
flux2 = read.table(data2,
                   row.names=1,
                   header=TRUE)
flux3 = read.table(data3,
                   row.names=1,
                   header=TRUE)
flux4 = read.table(data4,
                   row.names=1,
                   header=TRUE)



### (1-1) Create histogram of expression values in different samples

sampNum = 1      # Column number corresponding to sample of interest

hist1Data = data.frame(flux1[,sampNum])
hist_title = "DESeq2 Normalized"
hist1 = make_histogram1(hist1Data,
                        bin_num=50,
                        hist_title=hist_title)

hist2Data = data.frame(flux2[,sampNum])
hist_title = "Log10-DESeq2 Normalized"
hist2 = make_histogram1(hist2Data,
                        bin_num=50,
                        hist_title=hist_title)

hist3Data = data.frame(flux3[,sampNum])
hist_title = "TPM Normalized"
hist3 = make_histogram1(hist3Data,
                        bin_num=50,
                        hist_title=hist_title)

hist4Data = data.frame(flux4[,sampNum])
hist_title = "Log10-TPM Normalized"
hist4 = make_histogram1(hist4Data,
                        bin_num=50,
                        hist_title=hist_title)

combined_fig = hist1 + hist2 + hist3 + hist4
ggsave(paste('flux-histogram',hist_title,'_combined.pdf', sep=""),
       plot = combined_fig,
       width = 5, height = 5, units = "in")



### (1-2) Compare standard deviation across all genes




### (1-3) Perform PCA of samples using flux information

pcaData = t(flux1)
group = 
#pcaData = scale(pcaData)
plot_title = "DESeq2"
top_sd_feature_num = 200

# Acquires columns with the most variation
std_list = apply(pcaData, 2, sd)
ordered_std_idx = order(std_list,decreasing=TRUE)

std_list = std_list[ordered_std_idx]
pcaData = pcaData[,ordered_std_idx]
pcaData = pcaData[,c(1:top_sd_feature_num)]

pca_result = prcomp(pcaData,
                    center=TRUE,
                    scale.=TRUE)

pca_scores = as.data.frame(pca_result$x)
pca_scores$groups = c("1","1","1","2","2","2","3","3","3","4","4","4")

explained = round(100 * summary(pca_result)$importance[2,1:3], 1)

# 2-D PCA plot: PC1 vs PC2
pca_colors = c(
  rgb(0.7, 0, 0.8),
  rgb(0.9, 0.2, 0.7),
  rgb(0.5, 0.5, 0.5),
  rgb(0, 0, 0)
)
pca_fig = ggplot(pca_scores, 
                 aes(x = PC1, 
                     y = PC2, 
                     color = groups)) + 
  geom_point(size = 5) + 
  scale_color_manual(values = pca_colors) + 
  theme_bw() + 
  theme(
    axis.title = element_text(size=20),
    axis.text = element_text(size=20),
    plot.title = element_text(size=20, face="bold")
  ) +
  labs(
    title = paste('Flux PCA: ',plot_title, sep=""),
    x = paste0("PC1 (", explained[1], "%)"),
    y = paste0("PC2 (", explained[2], "%)")
  )

pca_fig

ggsave(paste('flux_pca',hist_title,'.pdf', sep=""),
       plot = pca_fig,
       width = 5, height = 5, units = "in")



# 3D PCA plot: PC1 vs PC2 vs PC3
pca_fig_3d = plot_ly(pca_scores,
                    x = ~PC1,
                    y = ~PC2,
                    z = ~PC3,
                    color = ~groups,
                    colors = pca_colors,
                    type = "scatter3d",
                    mode = "markers") %>%
  layout(
    title = paste0('Flux PCA-3D: ', plot_title),
    scene = list(
      title = list(title = 'test', titlefont = list(size = 30)),
      xaxis = list(title = paste0("PC1 (", explained[1], "%)"), titlefont = list(size = 12)),
      yaxis = list(title = paste0("PC2 (", explained[2], "%)"), titlefont = list(size = 12)),
      zaxis = list(title = paste0("PC3 (", explained[3], "%)"), titlefont = list(size = 12))
    )
  )
pca_fig_3d



#### (2) In the samples, how is glycolysis and lysine metabolism affected









```



3 - Downstream applications with the FLUX variable
```{r}


#compute pathway level activity for all samples
pathway = unique(unlist(human_gem$SUBSYSTEM))
pathway_score = list()
for (i in pathway){
  path = i
  activity_score = c()
  
  for (d in 1:ncol(flux)){
    activity_score[d] = mean(abs(flux[which(unlist(human_gem$SUBSYSTEM)==i),d]))
  }
  pathway_score[[i]] = activity_score
}
all_pathway_score = as.data.frame(do.call(rbind, pathway_score))

mapal <- colorRampPalette(RColorBrewer::brewer.pal(11,"RdBu"))(256)
pheatmap::pheatmap(all_pathway_score,cluster_cols = F,color = rev(mapal),scale = "row")

```


Differential flux analysis
```{r}
library(ggplot2)
library(METAFlux)

flux_data = "C:\\Users\\antho\\OneDrive\\Desktop\\Misc\\20240727_Sc7a1_RNAseq\\Analysis\\20250504_METAfluxAnalysis\\fluxOutputs\\flux_deseq2Norm.txt"
cond1 = c(10,11,12)    # gBdnf indices
cond2 = c(1,2,3)       # gSlc7a1 indices
#cond2 = c(4,5,6)       # gSlc7a1 + Lysine indices
#cond2 = c(7,8,9)       # gBdnf - Lysine indices
outputFile <- "gBdnf-v-gSlc7a1"


# Load data
flux_data = read.table(flux_data,
                       header = TRUE,
                       sep = "\t",
                       row.names = 1)

#### Predict varaince and standard error for Wald's test

flux_means = rowMeans(flux_data)
flux_vars = apply(flux_data, 1, var)

# Removes pathways with 0 variance
#exclude = which(flux_vars == 0)
#flux_means = flux_means[-exclude]
#flux_vars = flux_vars[-exclude]
#flux_data = flux_data[-exclude,]

fit = loess(flux_vars ~ flux_means,
            span = 0.15)

# Plot histogram of variances
var_hist = ggplot(data = as.data.frame(flux_vars),
                  aes(x = flux_vars)) + 
  geom_histogram(bins=50) + 
  scale_y_log10()

# Plot LOESS
df = data.frame(x = flux_means,
                y = flux_vars)
loess_plot = ggplot(df, aes(x = x,
                            y = y)) +
  geom_point(color = "gray") + 
  geom_smooth(method = "loess",
              span = 0.15,
              method.args = list(degree = 2),
              se = FALSE,
              color = "blue")


predicted_var = predict(fit, newdata = flux_means)
predicted_se = sqrt(predicted_var)
actual_se = sqrt(flux_vars)

#### Perform Wald's test using `predicted_se`

z_values = c()
p_values = c()
fdr_values = c()
diff_values = c()
for (i in 1:dim(flux_data)[1]) {
  flux1 = as.matrix(flux_data[i,cond1])
  flux2 = as.matrix(flux_data[i,cond2])
  
  mean_diff = mean(flux2) - mean(flux1)
  flux_se = predicted_se[i]
  #flux_se = actual_se[i]
  
  
  z_val = mean_diff/flux_se
  p_val = 2*pnorm(-abs(z_val))
  
  z_values = c(z_values, z_val)
  p_values = c(p_values, p_val)
  diff_values = c(diff_values, mean_diff)
}
fdr_values = p.adjust(p_values, method="BH")

# Plot volcano plot
volcano_data = data.frame(-log(fdr_values));
colnames(volcano_data) = "fdr"
volcano_data$diff = diff_values;
volcano_plot = ggplot(data = volcano_data,
                      aes(x = diff,
                          y = fdr)) +
  geom_point(size=3)

volcano_plot




data("human_gem")




```





